# prod profile - 운영 MySQL
spring.thymeleaf.cache=true
spring.web.resources.cache.cachecontrol.no-store=false

logging.level.root=INFO
logging.level.com.coresolution.cancertreatment=INFO

spring.datasource.url=${CANCER_TREATMENT_DATASOURCE_URL:jdbc:mysql://csm.sosyge.net:3306/csm?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
spring.datasource.username=${CANCER_TREATMENT_DATASOURCE_USERNAME:csdev}
spring.datasource.password=${CANCER_TREATMENT_DATASOURCE_PASSWORD:csdev1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=${CANCER_TREATMENT_SQL_INIT_MODE:never}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
