-- [2단계] Spring Session JDBC 스키마 (MySQL / InnoDB)
-- 출처: spring-session-jdbc 3.4.5 번들 org/springframework/session/jdbc/schema-mysql.sql 와 동일(verbatim).
--       (Spring Boot 3.4.10 이 관리하는 버전)
-- 적용 순서(롤백 안전): 이 DDL을 먼저 대상 DB(csm)에 적용한 뒤,
--   spring.session.store-type=jdbc + initialize-schema=never 로 앱을 배포한다.
--
--   mysql -h <host> -u <user> -p csm < scripts/spring-session-mysql.sql
--
-- 롤백: 설정에서 spring.session.* 제거(인메모리 복귀) 후 재배포.
--       테이블은 남겨둬도 무해(원하면 DROP TABLE SPRING_SESSION_ATTRIBUTES, SPRING_SESSION).

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
